/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#574500",
        "surface-bright": "#38393e",
        "inverse-on-surface": "#2f3035",
        "inverse-surface": "#e3e2e8",
        "tertiary": "#eecb6c",
        "error": "#ffb4ab",
        "outline-variant": "#4d4635",
        "surface-tint": "#e9c349",
        "on-secondary-container": "#ff9cad",
        "primary": "#f2ca50",
        "on-surface-variant": "#d0c5af",
        "tertiary-container": "#d0b054",
        "surface-container": "#1f1f24",
        "on-secondary-fixed-variant": "#782d3e",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#292a2e",
        "secondary": "#ffb2be",
        "surface": "#121317",
        "on-tertiary-fixed": "#241a00",
        "on-primary-fixed": "#241a00",
        "on-background": "#e3e2e8",
        "on-tertiary-container": "#564300",
        "surface-container-low": "#1a1b20",
        "primary-fixed-dim": "#e9c349",
        "secondary-fixed-dim": "#ffb2be",
        "error-container": "#93000a",
        "surface-variant": "#343439",
        "on-secondary-fixed": "#3f0114",
        "on-primary-container": "#554300",
        "tertiary-fixed-dim": "#e5c365",
        "on-tertiary": "#3d2f00",
        "tertiary-fixed": "#ffe08d",
        "surface-dim": "#121317",
        "secondary-container": "#7b2f40",
        "on-surface": "#e3e2e8",
        "primary-fixed": "#ffe088",
        "surface-container-highest": "#343439",
        "outline": "#99907c",
        "on-error": "#690005",
        "surface-container-lowest": "#0d0e12",
        "on-primary": "#3c2f00",
        "background": "#121317",
        "on-tertiary-fixed-variant": "#584400",
        "primary-container": "#d4af37",
        "secondary-fixed": "#ffd9de",
        "inverse-primary": "#735c00",
        "on-secondary": "#5b1729",
      },
      spacing: {
        "space-sm": "0.5rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        "space-md": "1rem",
        "margin": "3rem",
      },
      fontFamily: {
        "playfair": ["'Playfair Display'", "serif"],
        "jakarta": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero-mobile": ["'Playfair Display'", "serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "title-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-hero": ["'Playfair Display'", "serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        "title-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Playfair Display'", "serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["10px", { "lineHeight": "14px", "letterSpacing": "0.12em", "fontWeight": "700" }],
        "display-hero-mobile": ["38px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "52px", "letterSpacing": "-0.015em", "fontWeight": "500" }],
        "body-md": ["15px", { "lineHeight": "22px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "title-lg": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-hero": ["56px", { "lineHeight": "68px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "headline-sm": ["22px", { "lineHeight": "30px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "title-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
        "body-lg": ["17px", { "lineHeight": "26px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-lg-mobile": ["30px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-md": ["28px", { "lineHeight": "36px", "letterSpacing": "0em", "fontWeight": "500" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600" }],
      },
    },
  },
  plugins: [],
};
